on:
  pull_request_target:

jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    # git-auto-commit-action is a bit tricky to use.
    # See the "advanced" section in its README for an insecure configuration that works.
    #
    # To make it secure against malicious pull requests, you cannot trust files in the PR,
    # because pull_request_target jobs have more permissions than pull_request jobs.
    # Here we place the PR's stuff to a subdirectory named "pr".
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.head_ref }}
        path: ./pr
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: pip
    - run: pip install wheel
    # Be careful to not install arbitrary dependencies, install only the dependencies we really need and trust
    - run: pip install $(grep -E '^(black|isort|pycln)==[0-9.]*$' pr/requirements-dev.txt)
    - run: python3 -m pycln --all --disable-all-dunder-policy pr/mantaray pr/tests
    - run: python3 -m black pr/mantaray pr/tests
    - run: python3 -m isort pr/mantaray pr/tests
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        repository: ./pr
        commit_message: "Run pycln, black and isort"
