name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  license-year:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - run: |
        grep $(date +%Y) LICENSE
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: pip
    - run: pip install -r requirements.txt -r requirements-dev.txt
    - run: mypy mantaray
  dependencies-not-installed-error:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: (python3 -m mantaray || true) 2>&1 | tee output.txt
    - run: grep "You need to create a venv and install the dependencies into it with pip" output.txt
  test:
    strategy:
      matrix:
        # os is last so you can see everything in github's ui, even if the job name gets truncated
        irc-server: ["hircd", "mantatail"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20  # windows is slow
    env:
      IRC_SERVER: ${{ matrix.irc-server }}
    steps:
    - uses: actions/checkout@v3
    # https://stackoverflow.com/a/66919851
    - if: matrix.os == 'macos-latest'
      run: brew install python@3.9 python-tk@3.9
    - if: matrix.os != 'macos-latest'
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: pip
    - run: git submodule update --init
    # wheels seem to speed up other things on windows
    - run: python3 -m pip install wheel
    - run: python3 -m pip install -r requirements.txt
    - run: python3 -m pip install -r requirements-dev.txt
    - uses: GabrielBB/xvfb-action@v1.4
      with:
        run: python3 -m pytest -vv
