name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  license-year:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - run: |
        grep $(date +%Y) LICENSE
  ty:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        cache: pip
    - run: pip install wheel  # needed for sv-ttk to work
    - run: pip install -r requirements.txt -r requirements-dev.txt
    - run: ty check
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        cache: pip
    - run: pip install wheel  # needed for sv-ttk to work
    - run: pip install -r requirements.txt -r requirements-dev.txt
    - run: ruff check
  dependencies-not-installed-error:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
    - run: (python3 -m mantaray || true) 2>&1 | tee output.txt
    - run: grep "You need to create a venv and install the dependencies into it with pip" output.txt
  test-linux:
    strategy:
      matrix:
        irc-server: ["hircd", "mantatail"]
        shard: ["1/2", "2/2"]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      IRC_SERVER: ${{ matrix.irc-server }}
      MANTASHARD: ${{ matrix.shard }}
    steps:
    - uses: actions/checkout@v6
    # https://stackoverflow.com/a/66919851
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        cache: pip
    - run: git submodule update --init
    - run: python3 -m pip install wheel  # needed for sv-ttk to work
    - run: python3 -m pip install -r requirements.txt -r requirements-dev.txt
    - uses: GabrielBB/xvfb-action@v1.4
      with:
        run: python3 -m pytest -vv
  test-windows:
    strategy:
      matrix:
        irc-server: ["hircd", "mantatail"]
        shard: ["1/8", "2/8", "3/8", "4/8", "5/8", "6/8", "7/8", "8/8"]  # more shards on windows, because windows is slow
    runs-on: windows-latest
    timeout-minutes: 10
    env:
      IRC_SERVER: ${{ matrix.irc-server }}
      MANTASHARD: ${{ matrix.shard }}
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: "3.11"
        cache: pip
    - run: git submodule update --init
    - run: python3 -m pip install wheel  # needed for sv-ttk to work
    - run: python3 -m pip install -r requirements.txt -r requirements-dev.txt
    - run: python3 -m pytest -vv
  # TODO: enable macos tests again
#  test-macos:
#    strategy:
#      matrix:
#        irc-server: ["hircd", "mantatail"]
#        shard: ["1/2", "2/2"]
#    runs-on: ubuntu-latest
#    timeout-minutes: 10
#    env:
#      IRC_SERVER: ${{ matrix.irc-server }}
#      MANTASHARD: ${{ matrix.shard }}
#    steps:
#    - uses: actions/checkout@v6
#    # https://stackoverflow.com/a/66919851
#    - uses: actions/setup-python@v6
#      with:
#        python-version: "3.11"
#        cache: pip
#    - run: git submodule update --init
#    - run: python3 -m pip install wheel  # needed for sv-ttk to work
#    - run: python3 -m pip install -r requirements.txt -r requirements-dev.txt
#    - run: python3 -m pytest -vv
