on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pytest-macos:
    runs-on: macos-latest
    env:
      PYTHON: /usr/local/opt/python@3.9/libexec/bin/python
      PYTHONUNBUFFERED: 1
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: brew install python-tk@3.9
    - run: $PYTHON crash.py
