name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        # os is last so you can see everything in github's ui, even if the job name gets truncated
        irc-server: ["hircd", "mantatail"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      IRC_SERVER: ${{ matrix.irc-server }}
    steps:
    - uses: actions/checkout@v2
    # https://stackoverflow.com/a/66919851
    - if: matrix.os == 'macos-latest'
      run: brew install python@3.9 python-tk@3.9
    - if: matrix.os != 'macos-latest'
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: git submodule update --init
    # wheels seem to speed up other things on windows
    - run: python3 -m pip install wheel
    - run: python3 -m pip install -r requirements.txt
    - run: python3 -m pip install -r requirements-dev.txt
    - run: python3 -m pip install appdirs
    - run: python3 asd.py
