on:
  push:
    branches:
      - master
  pull_request:

jobs:
  license-year:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        grep $(date +%Y) LICENSE
  pyflakes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install -r requirements-dev.txt
    - run: pyflakes irc_client tests
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install -r requirements-dev.txt
    - run: python3 -m black --check irc_client tests
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"  # can be 3.10 once mypy is updated and no longer really slow on 3.10
    - run: pip install -r requirements-dev.txt
    - run: mypy irc_client
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install -r requirements-dev.txt
    - run: python3 -m pytest --capture=no
