name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  license-year:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - run: |
        grep $(date +%Y) LICENSE
  pyflakes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install -r requirements-dev.txt
    - run: pyflakes mantaray tests
  black:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: pip install -r requirements-dev.txt
    - run: python3 -m black --check mantaray tests
  mypy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"  # can be 3.10 once mypy is updated and no longer really slow on 3.10
    - run: pip install -r requirements-dev.txt
    - run: mypy mantaray
  test:
    strategy:
      matrix:
        # os is last so you can see everything in github's ui, even if the job name gets truncated
        irc-server: ["hircd", "mantatail"]
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    env:
      IRC_SERVER: ${{ matrix.irc-server }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - run: git submodule update --init
    # wheels seem to speed up other things on windows
    - run: pip install wheel
    - run: pip install -r requirements.txt
    - run: pip install -r requirements-dev.txt
    - uses: GabrielBB/xvfb-action@v1.4
      with:
        run: python3 -m pytest -vv
  pytest-macos:
    strategy:
      matrix:
        irc-server: ["hircd", "mantatail"]
    runs-on: macos-latest
    timeout-minutes: 10  # slower than on other platforms, because brew
    env:
      IRC_SERVER: ${{ matrix.irc-server }}
    steps:
    - uses: actions/checkout@v2
    # https://stackoverflow.com/a/66919851
    - run: brew install python@3.9
    - run: brew install python-tk@3.9
    - run: git submodule update --init
    - run: /usr/local/opt/python@3.9/libexec/bin/python -m pip install wheel
    - run: /usr/local/opt/python@3.9/libexec/bin/python -m pip install -r requirements.txt
    - run: /usr/local/opt/python@3.9/libexec/bin/python -m pip install -r requirements-dev.txt
    - run: /usr/local/opt/python@3.9/libexec/bin/python -m pytest -vv
